spring:
  application:
    name: Katsee

  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
      enabled: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PW}

  data:
    redis:
      port: 6379
      host: ${REDIS_HOST}
      repositories:
        enabled: false

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update

  thymeleaf:
    suffix: .html
    check-template-location: true
    cache: false
    mvc:
      static-path-pattern: "/static/**"

  web:
    resources:
      static-locations: classpath:/static/
  mvc:
    contentnegotiation:
      favor-path-extension: true

jwt:
  secret-key: ${JWT_SECRET_KEY}
  access-token-expire-time: ${JWT_ACCESS_EXPIRE_TIME}
  refresh-token-expire-time: ${JWT_REFRESH_EXPIRE_TIME}

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    s3:
      bucket: ${AWS_S3_BUCKET}
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false
